var N = null;var sourcesIndex = {};
sourcesIndex["chalk"] = {"name":"","files":["main.rs"]};
sourcesIndex["chalk_derive"] = {"name":"","files":["lib.rs"]};
sourcesIndex["chalk_engine"] = {"name":"","files":["context.rs","derived.rs","fallible.rs","forest.rs","hh.rs","lib.rs","logic.rs","simplify.rs","stack.rs","strand.rs","table.rs","tables.rs"]};
sourcesIndex["chalk_integration"] = {"name":"","files":["db.rs","error.rs","lib.rs","lowering.rs","program.rs","program_environment.rs","query.rs"]};
sourcesIndex["chalk_ir"] = {"name":"","dirs":[{"name":"fold","files":["binder_impls.rs","boring_impls.rs","shift.rs","subst.rs"]}],"files":["cast.rs","could_match.rs","debug.rs","fold.rs","interner.rs","lib.rs","macros.rs","tls.rs","zip.rs"]};
sourcesIndex["chalk_macros"] = {"name":"","files":["index.rs","lib.rs"]};
sourcesIndex["chalk_parse"] = {"name":"","files":["ast.rs","lib.rs"]};
sourcesIndex["chalk_rust_ir"] = {"name":"","files":["lib.rs"]};
sourcesIndex["chalk_solve"] = {"name":"","dirs":[{"name":"clauses","dirs":[{"name":"builtin_traits","files":["sized.rs"]}],"files":["builder.rs","builtin_traits.rs","env_elaborator.rs","program_clauses.rs"]},{"name":"coherence","files":["orphan.rs","solve.rs"]},{"name":"infer","files":["canonicalize.rs","instantiate.rs","invert.rs","normalize_deep.rs","ucanonicalize.rs","unify.rs","var.rs"]},{"name":"solve","dirs":[{"name":"slg","files":["aggregate.rs","resolvent.rs"]}],"files":["slg.rs","truncate.rs"]}],"files":["clauses.rs","coherence.rs","coinductive_goal.rs","ext.rs","goal_builder.rs","infer.rs","lib.rs","solve.rs","split.rs","wf.rs"]};
createSourceSidebar();
